apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: siibra-explorer-main-ingress
  labels:
    name: siibra-explorer-main-ingress
spec:
  rules:
  - host: siibra-explorer.apps.tc.humanbrainproject.eu
    http:
      paths:
      - pathType: Prefix
        path: "/viewer"
        backend:
          service:
            name: prod-siibra-explorer
            port: 
              number: 8080
      - pathType: Prefix
        path: "/viewer-staging"
        backend:
          service:
            name: rc-siibra-explorer
            port: 
              number: 8080
      - pathType: Prefix
        path: "/viewer-expmt"
        backend:
          service:
            name: expmt-siibra-explorer
            port: 
              number: 8080
  - host: siibra-explorer.apps.ebrains.eu
    http:
      paths:
      - pathType: Prefix
        path: "/viewer"
        backend:
          service:
            name: prod-siibra-explorer
            port: 
              number: 8080
      - pathType: Prefix
        path: "/viewer-staging"
        backend:
          service:
            name: rc-siibra-explorer
            port: 
              number: 8080
      - pathType: Prefix
        path: "/viewer-expmt"
        backend:
          service:
            name: expmt-siibra-explorer
            port: 
              number: 8080
  - host: atlases.ebrains.eu
    http:
      paths:
      - pathType: Prefix
        path: "/viewer"
        backend:
          service:
            name: prod-siibra-explorer
            port: 
              number: 8080
      - pathType: Prefix
        path: "/viewer-staging"
        backend:
          service:
            name: rc-siibra-explorer
            port: 
              number: 8080
      - pathType: Prefix
        path: "/viewer-expmt"
        backend:
          service:
            name: expmt-siibra-explorer
            port: 
              number: 8080
  tls:
  - secretName: siibra-explorer-prod-secret
    hosts:
    - siibra-explorer.apps.tc.humanbrainproject.eu
  - secretName: sxplr-ebrains-secret
    hosts:
    - siibra-explorer.apps.ebrains.eu
  - secretName: atlases-ebrains-secret
    hosts:
    - atlases.ebrains.eu
