---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emergency-fallback-cert
  labels:
    fallback: emergency
spec:
  secretName: sxplr-ppd-emergency-fallback-secret
  renewBefore: 120h 
  commonName: atlases.ebrains.eu
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  dnsNames:
  # (CHANGE ME! same as `commonName`)
  - atlases.ebrains.eu
  issuerRef:
    name: letsencrypt-production-issuer-1
    kind: ClusterIssuer 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: siibra-explorer-main-emergency-fallback-ingress
  labels:
    name: siibra-explorer-main-emergency-fallback-ingress
    fallback: emergency
  annotations:
    nginx.ingress.kubernetes.io/app-root: "/viewer"
spec:
  ingressClassName: nginx
  rules:
  - host: atlases.ebrains.eu
    http:
      paths:
      - pathType: Prefix
        path: "/viewer"
        backend:
          service:
            name: prod-siibra-explorer
            port: 
              number: 8080
      - pathType: Prefix
        path: "/viewer-dev"
        backend:
          service:
            name: dev-siibra-explorer
            port: 
              number: 8080
  tls:
  - secretName: sxplr-ppd-emergency-fallback-secret
    hosts:
    - atlases.ebrains.eu
