apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: siibra-explorer-certificate
spec:
  secretName: siibra-explorer-prod-secret
  renewBefore: 120h 
  commonName: siibra-explorer.apps.tc.humanbrainproject.eu
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  dnsNames:
  # (CHANGE ME! same as `commonName`)
  - siibra-explorer.apps.tc.humanbrainproject.eu
  issuerRef:
    name: letsencrypt-production-issuer-1
    kind: ClusterIssuer 