export { SapiViewsCoreParcellationModule } from "./module"
export { FilterGroupedParcellationPipe } from "./filterGroupedParcellations.pipe"
export { GroupedParcellation } from "./groupedParcellation"
export { ParcTmplDoiPipe } from "./parcTmplDoi.pipe"
export { ParcellationGroupSelectedPipe } from "./parcellationGroupSelected.pipe"
