pipeline {
  agent {
    node {
      label 'nodejs'
    }
  }

  environment {
    SERVICE_ACCOUNT_CRED = credentials('SERVICE_ACCOUNT_CRED')
    WAXHOLM_RAT_GOOGLE_SHEET_ID = credentials('WAXHOLM_RAT_GOOGLE_SHEET_ID')
    HUMAN_GOOGLE_SHEET_ID = credentials('HUMAN_GOOGLE_SHEET_ID')
    ATLAS_URL = 'https://interactive-viewer-next.apps-dev.hbp.eu/'
  }
  
  stages {
    stage('cd into deploy') {
      steps{
        dir('deploy')
      }
    }
    stage('Build') {
      steps {
        echo 'Building..'
        sh 'npm install'
      }
    }
    stage('Test available datasets') {
      parallel {
        stage('rat - v1.01') {
          steps {
            sh 'npm run mocha-env -- ./api-test/**/rat.v1_01.spec.js --timeout 60000'
          }
        }
        stage('rat - v2') {
          steps {
            sh 'npm run mocha-env -- ./api-test/**/rat.v2.spec.js --timeout 60000'
          }
        }
        stage('rat - v3') {
          steps {
            sh 'npm run mocha-env -- ./api-test/**/rat.v3.spec.js --timeout 60000'
          }
        }
        stage('mouse - 2015') {
          steps {
            sh 'npm run mocha-env -- ./api-test/**/mouse.2015.spec.js --timeout 60000'
          }
        }
        stage('mouse - 2017') {
          steps {
            sh 'npm run mocha-env -- ./api-test/**/mouse.2017.spec.js --timeout 60000'
          }
        }
        stage('human') {
          steps {
            sh 'echo NYI'
          }
        }
      }
    }
  }
}
