name: Trigger deploy with helm
on:
  workflow_call:

    inputs:
      DEPLOYMENT_NAME:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      IMAGE_DIGEST:
        required: false
        type: string
        default: 'default-digest'

    secrets:
      KUBECONFIG:
        required: true

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Deploy'
      run: |
        kubecfg_path=${{ runner.temp }}/.kube_config
        echo "${{ secrets.KUBECONFIG }}" > $kubecfg_path
        helm --kubeconfig=$kubecfg_path status ${{ inputs.DEPLOYMENT_NAME }}
        helm_status=$(echo $?)

        if [[ $helm_status = "0" ]]
        then
          echo "tag ${{ inputs.DEPLOYMENT_NAME }} found. Update"
          helm --kubeconfig=$kubecfg_path \
            upgrade \
            --set image.tag=${{ inputs.IMAGE_TAG }} \
            --set podLabels.image-digest=${{ inputs.IMAGE_DIGEST }} \
            ${{ inputs.DEPLOYMENT_NAME }} .helm/siibra-explorer/
        else
          echo "tag ${{ inputs.DEPLOYMENT_NAME }} not found. Install"
          helm --kubeconfig=$kubecfg_path \
            install \
            --set image.tag=${{ inputs.IMAGE_TAG }} \
            --set podLabels.image-digest=${{ inputs.IMAGE_DIGEST }} \
            ${{ inputs.DEPLOYMENT_NAME }} .helm/siibra-explorer/
        fi

        rm $kubecfg_path
