name: Trigger deploy with helm
on:
  workflow_call:

    inputs:
      IMAGE_TAG:
        required: true
        type: string

    secrets:
      KUBECONFIG:
        required: true

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Deploy'
      run: |
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube_config
        helm --kubeconfig=~/.kube_config status ${{ inputs.IMAGE_TAG }}
        helm_status=$(echo $?)

        if [[ $helm_status = "0" ]]
        then
          echo "tag ${{ inputs.IMAGE_TAG }} not found. Install"
          echo helm --kubeconfig=~/.kube_config install ${{ inputs.IMAGE_TAG }} .helm/siibra-explorer/
        else
          echo "tag ${{ inputs.IMAGE_TAG }} found. Update"
          echo helm --kubeconfig=~/.kube_config upgrade ${{ inputs.IMAGE_TAG }} .helm/siibra-explorer/
        fi

        rm ~/.kube_config
