name: "[cd] Trigger deploy with helm"
on:
  workflow_call:

    inputs:
      DEPLOYMENT_NAME:
        required: true
        type: string # prod, rc
      IMAGE_REPO:
        type: string
        default: 'docker-registry.ebrains.eu/siibra/siibra-explorer'
      IMAGE_TAG:
        required: true
        type: string
      IMAGE_DIGEST:
        required: false
        type: string
        default: 'default-digest'

    secrets:
      KUBECONFIG:
        required: true

jobs:
        
  trigger-deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ inputs.DEPLOYMENT_NAME == 'prod' }}
    steps:
    - uses: actions/checkout@v4
    - name: 'Deploy'
      run: |
        kubecfg_path=${{ runner.temp }}/.kube_config
        echo "${{ secrets.KUBECONFIG }}" > $kubecfg_path

        helm --kubeconfig=$kubecfg_path ls | awk '{print $1}' | grep -q ${{ inputs.DEPLOYMENT_NAME }} \
        && helm --kubeconfig=$kubecfg_path \
          upgrade \
          --history-max 3 \
          --set image.repository=${{ inputs.IMAGE_REPO }} \
          --set image.tag=${{ inputs.IMAGE_TAG }} \
          --set podAnnotations.image-digest=${{ inputs.IMAGE_DIGEST }} \
          ${{ inputs.DEPLOYMENT_NAME }} .helm/siibra-explorer/ \
        || helm --kubeconfig=$kubecfg_path \
          install\
          --set image.repository=${{ inputs.IMAGE_REPO }} \
          --set image.tag=${{ inputs.IMAGE_TAG }} \
          --set podAnnotations.image-digest=${{ inputs.IMAGE_DIGEST }} \
          ${{ inputs.DEPLOYMENT_NAME }} .helm/siibra-explorer/

        rm $kubecfg_path

  trigger-deploy-rc:
    runs-on: ubuntu-latest
    if: ${{ inputs.DEPLOYMENT_NAME == 'rc' }}
    steps:
    - uses: actions/checkout@v4
    - name: 'Deploy'
      run: |
        kubecfg_path=${{ runner.temp }}/.kube_config
        echo "${{ secrets.KUBECONFIG }}" > $kubecfg_path

        helm --kubeconfig=$kubecfg_path ls | awk '{print $1}' | grep -q ${{ inputs.DEPLOYMENT_NAME }} \
        && helm --kubeconfig=$kubecfg_path \
          upgrade \
          --history-max 3 \
          --reuse-values \
          --set image.repository=${{ inputs.IMAGE_REPO }} \
          --set image.tag=${{ inputs.IMAGE_TAG }} \
          --set envObj.OVERWRITE_API_ENDPOINT="https://siibra-api-rc.apps.ebrains.eu/v3_0" \
          --set podAnnotations.image-digest=${{ inputs.IMAGE_DIGEST }} \
          ${{ inputs.DEPLOYMENT_NAME }} .helm/siibra-explorer/ \
        || helm --kubeconfig=$kubecfg_path \
          install\
          --set image.repository=${{ inputs.IMAGE_REPO }} \
          --set image.tag=${{ inputs.IMAGE_TAG }} \
          --set podAnnotations.image-digest=${{ inputs.IMAGE_DIGEST }} \
          --set envObj.HOST_PATHNAME=/viewer-staging \
          --set envObj.OVERWRITE_API_ENDPOINT="https://siibra-api-rc.apps.ebrains.eu/v3_0" \
          ${{ inputs.DEPLOYMENT_NAME }} .helm/siibra-explorer/

        rm $kubecfg_path
