name: Trigger deploy with helm
on:
  workflow_call:

    inputs:
      IMAGE_TAG:
        required: true
        type: string

    secrets:
      KUBECONFIG:
        required: true

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Deploy'
      run: |
        export KUBECONFIG="${{ secrets.KUBECONFIG }}"
        helm status ${{ inputs.IMAGE_TAG }}
        helm_status=$(echo $?)

        if [[ $helm_status = "0" ]]
        then
          echo "tag ${{ inputs.IMAGE_TAG }} not found. Install"
          echo helm install ${{ inputs.IMAGE_TAG }} .helm/siibra-explorer/
        else
          echo "tag ${{ inputs.IMAGE_TAG }} found. Update"
          echo helm upgrade ${{ inputs.IMAGE_TAG }} .helm/siibra-explorer/
        fi
